
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=verbose
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
