
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "1998:80"
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
